# Generated by Django 5.2.6 on 2025-09-24 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('vk_url', models.URLField(blank=True, null=True, verbose_name='VK профиль')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram профиль')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube профиль')),
                ('tiktok_url', models.URLField(blank=True, null=True, verbose_name='TikTok профиль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('vk', 'VK'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Соцсеть')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='Комментарии')),
                ('videos', models.PositiveIntegerField(default=0, verbose_name='Видео')),
                ('views', models.PositiveBigIntegerField(default=0, verbose_name='Просмотры')),
                ('parsed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='analytics.blogger')),
            ],
            options={
                'ordering': ['-parsed_at'],
            },
        ),
    ]
