# Generated by Django 5.2.6 on 2025-09-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialstats',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
