# Generated by Django 5.2.6 on 2025-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_socialstats_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='blogger_id',
            field=models.CharField(default=1, max_length=255, verbose_name='Айди блогера'),
            preserve_default=False,
        ),
    ]
