# Generated by Django 5.2.6 on 2025-09-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_blogger_blogger_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='telegram_url',
            field=models.CharField(default=1, max_length=255, verbose_name='Ссылка телеграм'),
            preserve_default=False,
        ),
    ]
