# Generated by Django 5.2.6 on 2025-09-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_blogger_telegram_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='blogger_id',
            field=models.CharField(max_length=255, verbose_name='Creator №'),
        ),
    ]
