# Generated by Django 5.2.6 on 2025-09-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_blogger_blogger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='telegram_url',
            field=models.CharField(default='https://t.me/', max_length=255, verbose_name='Ссылка телеграм'),
        ),
    ]
