# Generated by Django 5.2.6 on 2025-10-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_blogger_telegram_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='first_name',
            field=models.CharField(db_collation='nocase', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='last_name',
            field=models.CharField(db_collation='nocase', max_length=100, verbose_name='Фамилия'),
        ),
    ]
