# Generated by Django 5.2.6 on 2025-10-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_blogger_first_name_alter_blogger_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='avatar_url',
            field=models.CharField(default=1, max_length=2500, verbose_name='URL Аватарки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogger',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
